version: '3'
services:  
  node:
    build:
      context: ./NodeBackEnd
      dockerfile: NodeDockerFile
      args:
        buildno: 1
    ports:
    - "3001:3000"
    networks:
    - front
  web-front:
    build:
      context: ./FrontEnd
      dockerfile: FrontDockerFile
      args:
        buildno: 1
    ports:
    - "80:80"
    links:
    - node
    networks:
    - front
networks:
  front:        
    driver: bridge
  back:
    driver: bridge