version: '3'
###########################################
services:  
  #--------------------------------------
  node:
    container_name: apartment_server
    build:
      context: ./NodeBackEnd
      dockerfile: NodeDockerFile
      args:        
        -  CONTAINER_PORT:${CONTAINER_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      CONTAINER_PORT: ${CONTAINER_PORT}
    ports:
    - ${HOST_PORT}:${CONTAINER_PORT}
    depends_on:
      - "mongodb"
    networks:
    - back
  #--------------------------------------
  mongodb:
    image: mongo:latest
    container_name: apartmentmongo
    networks:
      - back
    volumes:
      - E:\db_back:/data/db
  #--------------------------------------
  web-front:
    container_name: apartment_front
    build:
      context: ./FrontEnd
      dockerfile: FrontDockerFile
      args:
        buildno: 1
    ports:
    - "80:80"
    depends_on:
      - "mongodb"
      - "node"
    links:
    - node
    networks:
    - front
###########################################
networks:
  front:        
    driver: bridge
  back:
    driver: bridge