###########################################
version: '3'
###########################################
services:  
  #--------------------------------------
  mongodb:
    image: mongo:latest
    container_name: ${DB_CONTAINER_NAME}
    networks:
      - back
    ports:
    - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - mongo-dev-vol:/data/db
  #--------------------------------------
networks:
  back:
    driver: bridge
volumes:
  mongo-dev-vol: